In [ ]:
#data preprocessing
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, Normalizer

In [ ]:
#1. load dataset
iris=load_iris()

# convert to dataframe
x=pd.DataFrame(iris.data, columns=iris.feature_names)
y=pd.Series(iris.target, name='target')

print("Dataset shape:",x.shape)
print("Class Labels:", iris.target_names)

Dataset shape: (150, 4)
Class Labels: ['setosa' 'versicolor' 'virginica']

In [ ]:
#2. train test split
x_train, x_test, y_train, y_test=train_test_split(x, y, test_size=0.2, random_state=42)

In [ ]:
#3. scaling

scaler=StandardScaler()
x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.transform(x_test)

print("Scaling completed!")

Scaling completed!

In [ ]:
#4. Normalizing

normalizer=Normalizer()

x_train_normalized=normalizer.fit_transform(x_train_scaled)
x_test_normalized=normalizer.transform(x_test_scaled)
print("Normalization complete!")

Normalization complete!

In [ ]:
#5. final output
print("\n Final Preprocessed shape:")
print("x_trian_scaled", x_train_scaled.shape)
print("x_test_scaled", x_test_scaled.shape)
print("x_train_norm:",x_train_normalized.shape)
print("x_test_norm:",x_test_normalized.shape)

 Final Preprocessed shape:
x_trian_scaled (120, 4)
x_test_scaled (30, 4)
x_train_norm: (120, 4)
x_test_norm: (30, 4)

In [ ]:
x.isnull().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
dtype: int64

In [ ]:
Q1 = x.quantile(0.25)
Q3 = x.quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = x[(x < lower_bound) | (x > upper_bound)].dropna(how='all')

print("Outliers detected:")
if outliers.empty:
    print("No outliers found in the dataset using the IQR method.")
else:
    display(outliers)

Outliers detected:

    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
15                NaN               4.4                NaN               NaN
32                NaN               4.1                NaN               NaN
33                NaN               4.2                NaN               NaN
60                NaN               2.0                NaN               NaN

In [ ]:
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.preprocessing import OneHotEncoder

In [ ]:
#load dataset
iris=load_iris()
df=pd.DataFrame(iris.data, columns=iris.feature_names)
df["species"]=iris.target

In [ ]:
#mapping target values
df["species_name"]=df["species"].map({0:"setosa",1:"verginica",2:"versicolor"})
print("Original data shape:",df.shape)

Original data shape: (150, 6)

In [ ]:

def fing_outlier_IQR(data,column):
  Q1=data[column].quantile(0.25)
  Q3=data[column].quantile(0.75)
  IQR=Q3-Q1
  lower_limit=Q1-1.5*IQR
  upper_limit=Q3-1.5*IQR
return data[(data[column]<lower_limit)|(data[column]>upper_limit)]


outliers=pd.DataFrame()

for col in iris.features_names:
  outliers_col=pd.concat([outliers,fing_outlier_IQR(df,col)],axis=0)
outliers=outliers.drop_duplicates()
print("#n Detected Outliers")
print(outliers)
print("#n Number of Outliers",len(outliers))

SyntaxError: 'return' outside function (ipython-input-1348472513.py, line 7)